theme: jekyll-theme-minimal
title: "CMSE 402"
description: "This is the webpage for CMSE 402 for the Spring 2025 semester."
logo: /assets/img/logo.png

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock
